server:
  port: 8080
  servlet:
    contextPath: /${spring.application.name}/v1
spring:
  application:
    name: mssivimss-orden-entrada
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
  main:
    allow-circular-references: true
        
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
            
logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: error

endpoints:
   mod-catalogos: http://localhost:8094/mssivimss-mod-catalogos/v1/generico
   ms-reportes: http://localhost:8088/mssivimss-reportes-jasp/v1/generales/generar-reporte

reporte:
   consulta-orden-entrada: reportes/generales/CONSULTA_ORDEN_ENTRADA.jrxml
   consulta-stock: reportes/generales/CONSULTA_STOCK.jrxml   

jwt:
  secretkey-flujo: funcionamuybien
  secretkey-dominios: funcionamuybiendominio
  expiration-milliseconds: 36000
  
management:
      endpoints:
          web:
            exposure:
                include:
                    health,info,metrics

resilience4j.circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      msflujo:
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        failureRateThreshold: '50'
        slidingWindowType: COUNT_BASED
        event-consumer-buffer-size: '10'
        registerHealthIndicator: 'true'
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: '3'
        slidingWindowSize: '5'
resilience4j.retry:
    retryAspectOrder: 2
    instances:
        msflujo:
           maxAttempts: 3
           waitDuration: 5s
resilience4j.timelimiter:
    timeLimiterAspectOrder: 3
    instances:
      msflujo:
        timeout-duration: 3s
        
        
formato_fecha: '%d/%m/%Y'
ruta-log: 'C:\logs\'